apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollout-canary-public
  name: rollout-canary-public
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rollout-canary
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollout-canary-preview
  name: rollout-canary-preview
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rollout-canary
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollout-canary-stable
  name: rollout-canary-stable
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rollout-canary
  type: ClusterIP